CREATE TABLESPACE "BOD_TACO_TBS" OWNER postgres LOCATION '/bitnami/postgresql/BOD_TACO_TBS.NDF';

CREATE TABLESPACE "TACO_M00A" OWNER postgres LOCATION '/bitnami/postgresql/TACO_M00A.DBF';

CREATE TABLESPACE "TACO_M00B" OWNER postgres LOCATION '/bitnami/postgresql/TACO_M00B.DBF';

CREATE TABLESPACE "TACO_M01A" OWNER postgres LOCATION '/bitnami/postgresql/TACO_M01A.DBF';

CREATE TABLESPACE "TACO_M01B" OWNER postgres LOCATION '/bitnami/postgresql/TACO_M01B.DBF';

CREATE TABLESPACE "TACO_M04A" OWNER postgres LOCATION '/bitnami/postgresql/TACO_M04A.DBF';

CREATE TABLESPACE "TACO_M04B"  OWNER postgres LOCATION '/bitnami/postgresql/TACO_M04B.DBF';

CREATE TABLESPACE "TACO_U" OWNER postgres LOCATION '/bitnami/postgresql/TACO_U.DBF';