CREATE TABLESPACE DBENG_U DATAFILE 'dbeng_u.dbf' SIZE 50m; 

CREATE TABLESPACE DBENG_M00A DATAFILE 'dbeng_m00a.dbf' SIZE 50m;
CREATE TABLESPACE DBENG_M00B DATAFILE 'dbeng_m00b.dbf' SIZE 50m;

CREATE TABLESPACE DBENG_M01A DATAFILE 'dbeng_m01a.dbf' SIZE 50m;
CREATE TABLESPACE DBENG_M01B DATAFILE 'dbeng_m01b.dbf' SIZE 50m;

CREATE TABLESPACE DBENG_M02A DATAFILE 'dbeng_m02a.dbf' SIZE 50m;
CREATE TABLESPACE DBENG_M02B DATAFILE 'dbeng_m02b.dbf' SIZE 50m;

CREATE TABLESPACE DBENG_M04A DATAFILE 'dbeng_m04a.dbf' SIZE 50m;
CREATE TABLESPACE DBENG_M04B DATAFILE 'dbeng_m04b.dbf' SIZE 50m;

CREATE TABLESPACE DBENG_M05A DATAFILE 'dbeng_m05a.dbf' SIZE 50m;
CREATE TABLESPACE DBENG_M05B DATAFILE 'dbeng_m05b.dbf' SIZE 50m;

CREATE TABLESPACE DBENG_M06A DATAFILE 'dbeng_m06a.dbf' SIZE 50m;
CREATE TABLESPACE DBENG_M06B DATAFILE 'dbeng_m06b.dbf' SIZE 50m;

CREATE TABLESPACE DBENG_M07A DATAFILE 'dbeng_m07a.dbf' SIZE 50m;
CREATE TABLESPACE DBENG_M07B DATAFILE 'dbeng_m07b.dbf' SIZE 50m;
