CREATE TABLESPACE "BOD_TACO_TBS" LOCATION 'F:\\POSTGRESQL\\9.6\\DATA\\BOD_TACO_TBS.NDF';

CREATE TABLESPACE "TACO_M00A" OWNER postgres LOCATION 'F:\\POSTGRESQL\\9.6\\DATA\\TACO_M00A.DBF';

CREATE TABLESPACE "TACO_M00B" OWNER postgres LOCATION 'F:\\POSTGRESQL\\9.6\\DATA\\TACO_M00B.DBF';

CREATE TABLESPACE "TACO_M01A" OWNER postgres LOCATION 'F:\\POSTGRESQL\\9.6\\DATA\\TACO_M01A.DBF';

CREATE TABLESPACE "TACO_M01B" OWNER postgres LOCATION 'F:\\POSTGRESQL\\9.6\\DATA\\TACO_M01B.DBF';

CREATE TABLESPACE "TACO_M04A" OWNER postgres LOCATION 'F:\\POSTGRESQL\\9.6\\DATA\\TACO_M04A.DBF';

CREATE TABLESPACE "TACO_M04B" OWNER postgres LOCATION 'F:\\POSTGRESQL\\9.6\\DATA\\TACO_M04B.DBF';

CREATE TABLESPACE "TACO_U" OWNER postgres LOCATION 'F:\\POSTGRESQL\\9.6\\DATA\\TACO_U.DBF';