CREATE TABLESPACE "BOD_TACO_TBS" OWNER postgres LOCATION 'E:\PostgreSQL\9.6\data\BOD_TACO_TBS.NDF';

CREATE TABLESPACE "TACO_M00A" OWNER postgres LOCATION 'E:\PostgreSQL\9.6\data\TACO_M00A.DBF';

CREATE TABLESPACE "TACO_M00B" OWNER postgres LOCATION 'E:\PostgreSQL\9.6\data\TACO_M00B.DBF';

CREATE TABLESPACE "TACO_M01A" OWNER postgres LOCATION 'E:\PostgreSQL\9.6\data\TACO_M01A.DBF';

CREATE TABLESPACE "TACO_M01B" OWNER postgres LOCATION 'E:\PostgreSQL\9.6\data\TACO_M01B.DBF';

CREATE TABLESPACE "TACO_M04A" OWNER postgres LOCATION 'E:\PostgreSQL\9.6\data\TACO_M04A.DBF';

CREATE TABLESPACE "TACO_M04B"  OWNER postgres LOCATION 'E:\PostgreSQL\9.6\data\TACO_M04B.DBF';

CREATE TABLESPACE "TACO_U" OWNER postgres LOCATION 'E:\PostgreSQL\9.6\data\TACO_U.DBF';