CREATE TABLESPACE "BOD_TACO_TBS" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/BOD_TACO_TBS.NDF';
CREATE TABLESPACE "TACO_M00A" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/TACO_M00A.DBF';
CREATE TABLESPACE "TACO_M00B" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/TACO_M00B.DBF';
CREATE TABLESPACE "TACO_M01A" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/TACO_M01A.DBF';
CREATE TABLESPACE "TACO_M01B" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/TACO_M01B.DBF';
CREATE TABLESPACE "TACO_M04A" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/TACO_M04A.DBF';
CREATE TABLESPACE "TACO_M04B"  OWNER postgres LOCATION '/usr/pg/usr_tblspcs/TACO_M04B.DBF';
CREATE TABLESPACE "TACO_U" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/TACO_U.DBF';

CREATE TABLESPACE "DBENG_M00A" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/DBENG_M00A.DBF';
CREATE TABLESPACE "DBENG_M00B" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/DBENG_M00B.DBF';
CREATE TABLESPACE "DBENG_M01A" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/DBENG_M01A.DBF';
CREATE TABLESPACE "DBENG_M01B" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/DBENG_M01B.DBF';
CREATE TABLESPACE "DBENG_M02A" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/DBENG_M02A.DBF';
CREATE TABLESPACE "DBENG_M02B" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/DBENG_M02B.DBF';
CREATE TABLESPACE "DBENG_M04A" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/DBENG_M04A.DBF';
CREATE TABLESPACE "DBENG_M04B" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/DBENG_M04B.DBF';
CREATE TABLESPACE "DBENG_M05A" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/DBENG_M05A.DBF';
CREATE TABLESPACE "DBENG_M05B" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/DBENG_M05B.DBF';
CREATE TABLESPACE "DBENG_M06A" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/DBENG_M06A.DBF';
CREATE TABLESPACE "DBENG_M06B" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/DBENG_M06B.DBF';
CREATE TABLESPACE "DBENG_M07A" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/DBENG_M07A.DBF';
CREATE TABLESPACE "DBENG_M07B" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/DBENG_M07B.DBF';

CREATE TABLESPACE "BOD_ENI_TBS" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/BOD_ENI_TBS';
CREATE TABLESPACE "BOD_TMS_TBS" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/BOD_TMS_TBS';
CREATE TABLESPACE "202109_01_M00A" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/202109_01_M00A';
CREATE TABLESPACE "202109_01_M00B" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/202109_01_M00B';
CREATE TABLESPACE "202109_01_M01A" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/202109_01_M01A';
CREATE TABLESPACE "202109_01_M01B" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/202109_01_M01B';
CREATE TABLESPACE "202109_01_U" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/202109_01_U';
CREATE TABLESPACE "ENI_ENG_M00A" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/ENI_ENG_M00A';
CREATE TABLESPACE "ENI_ENG_M00B" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/ENI_ENG_M00B';
CREATE TABLESPACE "ENI_ENG_M01A" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/ENI_ENG_M01A';
CREATE TABLESPACE "ENI_ENG_M01B" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/ENI_ENG_M01B';
CREATE TABLESPACE "ENI_ENG_U" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/ENI_ENG_U';

CREATE TABLESPACE "TMS_PG_M00A" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/TMS_PG_M00A';
CREATE TABLESPACE "TMS_PG_M00B" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/TMS_PG_M00B';
CREATE TABLESPACE "TMS_PG_M06A" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/TMS_PG_M06A';
CREATE TABLESPACE "TMS_PG_M06B" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/TMS_PG_M06B';
CREATE TABLESPACE "TMS_PG_U" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/TMS_PG_U';
CREATE TABLESPACE "EXYTE_U" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/EXYTE_U';

CREATE TABLESPACE "DAN_EQP_U" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/DAN_EQP_U';
CREATE TABLESPACE "DAN_EQP_M00A" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/DAN_EQP_M00A';
CREATE TABLESPACE "DAN_EQP_M00B" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/DAN_EQP_M00B';
CREATE TABLESPACE "DAN_EQP_M01A" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/DAN_EQP_M01A';
CREATE TABLESPACE "DAN_EQP_M01B" OWNER postgres LOCATION '/usr/pg/usr_tblspcs/DAN_EQP_M01B';

CREATE ROLE "BOD_TACO" WITH
  LOGIN
  SUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'md500c8cee69e04687ecf4b0fa6bc547e97';

CREATE ROLE "TACO" WITH
  LOGIN
  SUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'md523d4c9c38e912f34c7d6bb28fcdd87a4';

CREATE ROLE "DBENG" WITH
  LOGIN
  SUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'md500c8cee69e04687ecf4b0fa6bc547e97';
  
CREATE ROLE "BOD_ENI" WITH LOGIN ENCRYPTED PASSWORD 'md5c07cd8a135f823d2c25261093dcfccdf' SUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE "BOD_TMS" WITH LOGIN ENCRYPTED PASSWORD 'md535e9138993052d2753a805add3f6670f' SUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE "202109_01" WITH LOGIN ENCRYPTED PASSWORD 'md56c0cd4dc67b46f45a79a08d23f8ff3fe' SUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE "ENI_ENG" WITH LOGIN ENCRYPTED PASSWORD 'md5a26cb51dc4191a13ff29e7173242ca74' SUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE "TMS_PG" WITH LOGIN ENCRYPTED PASSWORD 'md50bed7ef4e806bab8f93ef1ebfa5c3787' SUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE "EXYTE" WITH LOGIN ENCRYPTED PASSWORD 'md50bed7ef4e806bab8f93ef1ebfa5c3787' SUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE "DAN_EQP" WITH LOGIN ENCRYPTED PASSWORD 'md50bed7ef4e806bab8f93ef1ebfa5c3787' SUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;